Add queen bee. Closes #3
Talioo/Hive pull request #10
Opened 2019-10-07 14:53 UTC by Talioo

2019-10-08 06:47 UTC, Talioo commented
@WhimsySoftware @WhimsySoftwareTech  просто на случай если на почту не пришло письмо

2019-10-08 15:14 UTC, WhimsySoftware commented on Hive/Assets/Scripts/HiveMembers/HiveMember.cs
> +        if (MoveType == MoveType.Crawl) StartCoroutine(CrawlToTarget(newCell));
на майбтунє - розділяй в 2 строички, так якшо шо дебажити буде краще

2019-10-08 15:16 UTC, WhimsySoftware requested changes

2019-10-08 15:16 UTC, WhimsySoftware commented on Hive/Assets/Scripts/HiveMembers/QueenBee.cs
> +        GetCell(transform.position + (Vector3.forward + Vector3.left * 2));
це якась дічь)) придумай інший спосіб..це не раціональне рішення

2019-10-08 15:16 UTC, WhimsySoftware commented on Hive/Assets/Scripts/HiveMembers/QueenBee.cs
> +        Gizmos.DrawLine(transform.position, transform.position + (Vector3.forward + Vector3.left * 2));
тут те саме

2019-10-08 15:16 UTC, WhimsySoftware commented on Hive/Assets/Scripts/HiveMembers/QueenBee.cs
> +    }
попробуй замінии цей спосіб без райкаста...попробуй зробити оті елементи як об'єкти

2019-10-08 15:16 UTC, WhimsySoftware commented on Hive/Assets/Scripts/SOHexaInfo.cs
> +        return freeCells;
тут зразу можна зробити ретурк якшо ти так робиш

2019-10-09 07:42 UTC, Talioo commented on Hive/Assets/Scripts/HiveMembers/QueenBee.cs
> +        GetCell(transform.position + (Vector3.forward + Vector3.left * 2));
В #13 я сделала массив соседей. По сути, он спокойно может заменить и эту структуру и рейкасты, Тем более завязочки к нему я уже делала (HiveMember -> HexaCell myCell;)
Так что можно отказаться от этой дичи вполне безболезненно. Сделала таску #14 для этого.

2019-10-09 07:42 UTC, Talioo commented on Hive/Assets/Scripts/HiveMembers/QueenBee.cs
> +        Gizmos.DrawLine(transform.position, transform.position + (Vector3.forward + Vector3.left * 2));
Было больше для наглядности. Уже нет необходимости, удалила

2019-10-09 07:57 UTC, Talioo commented on Hive/Assets/Scripts/SOHexaInfo.cs
> +        return freeCells;
Сделала. Действительно получилось лучше

2019-10-09 11:03 UTC, closed without merging