Add UI for hive members. Closes #11
Talioo/Hive pull request #12
Opened 2019-10-08 09:49 UTC by Talioo

2019-10-08 15:18 UTC, WhimsySoftware requested changes

2019-10-08 15:18 UTC, WhimsySoftware commented on Hive/Assets/Scripts/SOInstances.cs
> +        if (UIController == null) UIController = _UIController;
розбий на більше рядочків))

2019-10-08 15:18 UTC, WhimsySoftware commented on Hive/Assets/Scripts/SOInstances.cs
> +
видаляй не потріюні пробіли) це твоє обличчя

2019-10-08 15:18 UTC, WhimsySoftware commented on Hive/Assets/Scripts/Shining.cs
> +    private static Image image;
нарушення ООП. Нашо тобі це поле статичне? тут має робити роботу цю менеджер якийсь. нарушення логіки

2019-10-09 07:05 UTC, Talioo commented
Я сейчас сделаю ещё одну ветку чтобы не было конфликтов при коммите и сделаю ещё один реквест

2019-10-09 07:13 UTC, WhimsySoftware approved these changes

2019-10-09 07:23 UTC, merged