Bugfix
Talioo/Hive pull request #23
Opened 2019-10-18 14:58 UTC by Talioo

1) Предыдущий реквест можешь не смотреть, он уже не актуален
2) Класс QueenBee теперь пустой. Это не на долго, в следующих тасках добавлю функционала, так что его не удаляла
3) Есть класс с русскими комментами - это алгоритм работы спэшл фо ю. Позже или удалю комменты, или переведу их на англ, пока так

2019-10-18 15:09 UTC, WhimsySoftware requested changes

2019-10-18 15:09 UTC, WhimsySoftware commented on Hive/Assets/Scripts/CellNumerator.cs
> +        for (int i = 0; i < 6; i++)
чого 6? в константу..бажано всьо в глобал..

2019-10-18 15:09 UTC, WhimsySoftware commented on Hive/Assets/Scripts/CellNumerator.cs
> +            if (Vector3.Distance(HexaCell.availableCells[i].transform.position, neighbour.transform.position) < 0.15f)
чого 0 15?

2019-10-18 15:09 UTC, WhimsySoftware commented on Hive/Assets/Scripts/CellNumerator.cs
> +            if (Vector3.Distance(currentCell.neighbours[i].transform.position, empty.transform.position) < 0.15f)
а не простіше винести оцю строчку в метод, і її дьоргати?

2019-10-21 11:18 UTC, Talioo commented on Hive/Assets/Scripts/CellNumerator.cs
> +            if (Vector3.Distance(HexaCell.availableCells[i].transform.position, neighbour.transform.position) < 0.15f)
Из-за масштаба АР все объекты уменьшены в 10 раз. Это расстояние меньше чем до середины любой другой ячейки кроме первой верхней, которая мне и нужна

2019-10-21 11:54 UTC, WhimsySoftware approved these changes

2019-10-21 11:54 UTC, merged